# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
  pull_request: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.72.1
        with:
          ruby-version: 3.0.1
      - name: Install InfluxDB OSS
        run: |
          cd /tmp
          wget https://dl.influxdata.com/platform/nightlies/influx_nightly_linux_amd64.tar.gz
          tar xvfz influx_nightly_linux_amd64.tar.gz || true
          sudo cp influx_nightly_linux_amd64/{influx,influxd} /usr/local/bin/
      - name: Start and Configure InfluxDB
        run: |
          influxd --http-bind-address :8086 --reporting-disabled > /dev/null 2>&1 &
          until curl -s http://localhost:8086/health; do sleep 1; done
          influx setup --host http://localhost:8086 -f -b dummy -o influxdata -u ci_user -p password
      - name: Generate LP
        run: |
          cd $GITHUB_WORKSPACE/air-sensor-data
          ruby ./air-sensor-data.rb > ./air-sensor-data.lp
      - name: Load Data to InfluxDB OSS
        run: |
          /usr/local/bin/influx write -f ./air-sensor-data.lp -b dummy
      - name: Query Data from InfluxDB OSS
        run: |
          /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y)" --raw > ./air-sensor-data-annotated.csv
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Russ Savage
          author_email: russ@influxdata.com
          message: 'Adding LP and annotated CSV file'
